INSERT INTO authusers.oauth_client_details (client_id, resource_ids, client_secret, scope, authorized_grant_types, web_server_redirect_uri, authorities, access_token_validity, refresh_token_validity, additional_information, autoapprove) VALUES ('_CsfltCDjn-RPgxf6hHEjetUIYQDaMa8gM5hpqE-j2A', null, '$2a$10$WIg2MPoos1wbcT5nYzJIbeaCkmRk9pftVboHCaIONuolSzvNHJw7W', 'server', 'refresh_token,client_credentials', null, '', 36000, 360000, null, 'true');
INSERT INTO authusers.oauth_client_details (client_id, resource_ids, client_secret, scope, authorized_grant_types, web_server_redirect_uri, authorities, access_token_validity, refresh_token_validity, additional_information, autoapprove) VALUES ('94IViWOlyjr_vKhFTiUgLvMR0JeF4IjUXGD0T_HVELU', null, '$2a$10$djOGdcGVUr.WVxn1oZvqOu3rAShrmtrc9JFcXlnQzx/DsmHKJ/bjW', 'server', 'refresh_token,client_credentials', null, '', 36000, 360000, null, 'true');
INSERT INTO authusers.oauth_client_details (client_id, resource_ids, client_secret, scope, authorized_grant_types, web_server_redirect_uri, authorities, access_token_validity, refresh_token_validity, additional_information, autoapprove) VALUES ('Jf9r3o_0k2XFhQGBjob3Uea1Uhg8b3-z7eG2nP0djUc', null, '$2a$10$qrxQSmyKFVM1pha5AzAejOedcibj4SUT0cq8H/DR1Ia9LZa./eCjO', 'server', 'refresh_token,client_credentials', null, '', 36000, 360000, null, 'true');
INSERT INTO authusers.oauth_client_details (client_id, resource_ids, client_secret, scope, authorized_grant_types, web_server_redirect_uri, authorities, access_token_validity, refresh_token_validity, additional_information, autoapprove) VALUES ('oauthorize', null, '$2a$10$uvgzdEDFLl9mSCAWK6w.i.ZIZ7eSizqziPly.nOWpAUvZ1Mp3LYju', 'read,write', 'password,refresh_token,client_credentials', null, null, 36000, 360000, null, 'true');
INSERT INTO authusers.oauth_client_details (client_id, resource_ids, client_secret, scope, authorized_grant_types, web_server_redirect_uri, authorities, access_token_validity, refresh_token_validity, additional_information, autoapprove) VALUES ('oYIfyd1Hnoc5nPC5B2N9OZhrs-SHoe9kVeUJ9HCYoWI', null, '$2a$10$C5qitI52j1b4bllEOZSzOeEY7hrNOrRjClor1cKZecCuFl64foWUO', 'server', 'refresh_token,client_credentials', null, '', 36000, 360000, null, 'true');
INSERT INTO authusers.oauth_client_details (client_id, resource_ids, client_secret, scope, authorized_grant_types, web_server_redirect_uri, authorities, access_token_validity, refresh_token_validity, additional_information, autoapprove) VALUES ('Zd7AmbccoV18ig7f9Kv7IuRCU8sAb25KqbDsQQ-_KgE', null, '$2a$10$uMUwH4IRs5i6HDd82Iz9lef6tjhkmiifvBfKydwliuFGfTIIX4qy6', 'server', 'refresh_token,client_credentials', null, '', 36000, 360000, null, 'true');
INSERT INTO authusers.role (id, name) VALUES (1, 'ROLE_USER');
INSERT INTO authusers.user (id, email, first_name, is_enabled, is_verified, last_name, last_password_reset_date, password, username) VALUES (1, 'mail@mail.com', 'Mix', true, true, 'Mixovic', null, '$2a$10$7B.bVqK2UMz90G0qKdqbj.e28j7iuLFUCxmF/tzC5dlUIoQbPFUjy', 'mixa');
INSERT INTO authusers.user (id, email, first_name, is_enabled, is_verified, last_name, last_password_reset_date, password, username) VALUES (4, 'd1476273@urhen.com', 'Marko', true, true, 'Markovic', null, '$2a$10$F9mX8eMrgXFOLvWf0xGrreAHtB60JvpgwDv2Z2ux0idKM64jxnAJe', 'marko');
INSERT INTO authusers.user (id, email, first_name, is_enabled, is_verified, last_name, last_password_reset_date, password, username) VALUES (6, 'd1486501@urhen.com', 'Jovan', true, true, 'Jovanovic', null, '$2a$10$VuI2.5hxTbaWwwXz003YFekmdkv3oTdu3KjxZ5/w1WDc2DFc7NLFS', 'jovan');
INSERT INTO authusers.user_roles (user_id, role_id) VALUES (1, 1);
INSERT INTO authusers.user_roles (user_id, role_id) VALUES (4, 1);
INSERT INTO authusers.user_roles (user_id, role_id) VALUES (6, 1);
INSERT INTO bank.account (id, amount, card_holder_name, card_number, cvv, expiration_date) VALUES (1, 200000, 'Veljko Mosorinski', '4381634575122764', '124', '2021-01-01 05:00:00');
INSERT INTO bank.account (id, amount, card_holder_name, card_number, cvv, expiration_date) VALUES (2, 99978, 'Milica Matijevic', '4381637093394898', '125', '2020-09-01 05:00:00');
INSERT INTO bank.account (id, amount, card_holder_name, card_number, cvv, expiration_date) VALUES (3, 144975, 'Mihajlo Levarski', '4381639522238415', '127', '2024-08-01 05:00:00');
INSERT INTO bank.account (id, amount, card_holder_name, card_number, cvv, expiration_date) VALUES (4, 1002482, 'Marko Markovic', '4381639139847699', '128', '2022-02-01 05:00:00');
INSERT INTO bank.merchant (merchant_id, merchant_password, account_id) VALUES ('RWUKBtlFRnQqPDdfoOy8sop36Vo', '9ZPHH0VfaqBURrsO4_O1RDR6Q2aaqb5P4pDlW0gs5SrMnYWtvMuQEisPbZOtv5zsB0qSfEJg47I9NUY7', 4);
INSERT INTO bank.transaction_type (id, name) VALUES (1, 'CREDIT');
INSERT INTO bank.transaction_type (id, name) VALUES (2, 'DEBIT');
INSERT INTO banksecond.account (id, amount, card_holder_name, card_number, cvv, expiration_date) VALUES (5, 563974, 'Ana Milic', '4062211146650783', '231', '2023-03-01 05:00:00');
INSERT INTO banksecond.account (id, amount, card_holder_name, card_number, cvv, expiration_date) VALUES (6, 46989, 'Nemanja Milankovic', '4062216656489308', '547', '2025-07-01 05:00:00');
INSERT INTO banksecond.account (id, amount, card_holder_name, card_number, cvv, expiration_date) VALUES (7, 55989, 'Nikolina Matic', '4062214192891632', '364', '2021-06-01 05:00:00');
INSERT INTO banksecond.account (id, amount, card_holder_name, card_number, cvv, expiration_date) VALUES (8, 22988, 'Marina Cosic', '4062211743800773', '145', '2021-02-01 05:00:00');
INSERT INTO banksecond.transaction_type (id, name) VALUES (1, 'DEBIT');
INSERT INTO banksecond.transaction_type (id, name) VALUES (2, 'CREDIT');
INSERT INTO bankservice.client (id, client_id, merchant_id, merchant_password) VALUES (4, '_CsfltCDjn-RPgxf6hHEjetUIYQDaMa8gM5hpqE-j2A', 'RWUKBtlFRnQqPDdfoOy8sop36Vo', '9ZPHH0VfaqBURrsO4_O1RDR6Q2aaqb5P4pDlW0gs5SrMnYWtvMuQEisPbZOtv5zsB0qSfEJg47I9NUY7');
INSERT INTO naucna_c.magazine (id, issn, name, price, reader_pays) VALUES (1, 'issn1', 'Casopis 1', 20, true);
INSERT INTO naucna_c.magazine (id, issn, name, price, reader_pays) VALUES (2, 'issn2', 'Casopis 2', 22, false);
INSERT INTO naucna_c.magazine (id, issn, name, price, reader_pays) VALUES (3, 'issn3', 'Casopis 3', 37, true);
INSERT INTO naucna_c.magazine (id, issn, name, price, reader_pays) VALUES (4, 'issn4', 'Casopis 4', 50, false);
INSERT INTO naucna_c.magazine (id, issn, name, price, reader_pays) VALUES (5, 'issn5', 'Casopis 5', 11, true);
INSERT INTO naucna_c.magazine (id, issn, name, price, reader_pays) VALUES (6, 'issn6', 'Casopis 6', 12, false);
INSERT INTO naucna_c.magazine (id, issn, name, price, reader_pays) VALUES (7, 'issn7', 'Casopis 7', 15.5, true);
INSERT INTO naucna_c.magazine (id, issn, name, price, reader_pays) VALUES (8, 'issn8', 'Casopis 8', 13, false);
INSERT INTO naucna_c.magazine_scientific_area (magazine_list_id, scientific_area_id) VALUES (1, 1);
INSERT INTO naucna_c.magazine_scientific_area (magazine_list_id, scientific_area_id) VALUES (1, 5);
INSERT INTO naucna_c.magazine_scientific_area (magazine_list_id, scientific_area_id) VALUES (2, 2);
INSERT INTO naucna_c.magazine_scientific_area (magazine_list_id, scientific_area_id) VALUES (3, 1);
INSERT INTO naucna_c.magazine_scientific_area (magazine_list_id, scientific_area_id) VALUES (3, 4);
INSERT INTO naucna_c.magazine_scientific_area (magazine_list_id, scientific_area_id) VALUES (4, 2);
INSERT INTO naucna_c.magazine_scientific_area (magazine_list_id, scientific_area_id) VALUES (4, 5);
INSERT INTO naucna_c.magazine_scientific_area (magazine_list_id, scientific_area_id) VALUES (5, 5);
INSERT INTO naucna_c.magazine_scientific_area (magazine_list_id, scientific_area_id) VALUES (6, 3);
INSERT INTO naucna_c.magazine_scientific_area (magazine_list_id, scientific_area_id) VALUES (6, 1);
INSERT INTO naucna_c.magazine_scientific_area (magazine_list_id, scientific_area_id) VALUES (7, 1);
INSERT INTO naucna_c.magazine_scientific_area (magazine_list_id, scientific_area_id) VALUES (8, 4);
INSERT INTO naucna_c.publication (id, description, no, price, title, magazine_id) VALUES (1, 'Ovo je description od izdanja 1', 1, 5, 'Necete verovati sta se desilo!', 1);
INSERT INTO naucna_c.publication (id, description, no, price, title, magazine_id) VALUES (2, 'Ovo je description od izdanja 2', 2, 6, 'Necete verovati sta se opet desilo!', 1);
INSERT INTO naucna_c.role (id, name) VALUES (1, 'ROLE_USER');
INSERT INTO naucna_c.scentific_area (id, name) VALUES (1, 'Area 1');
INSERT INTO naucna_c.scentific_area (id, name) VALUES (2, 'Area 2');
INSERT INTO naucna_c.scentific_area (id, name) VALUES (3, 'Area 3');
INSERT INTO naucna_c.scentific_area (id, name) VALUES (4, 'Area 4');
INSERT INTO naucna_c.scentific_area (id, name) VALUES (5, 'Area 5');
INSERT INTO naucna_c.scentific_area (id, name) VALUES (6, 'Area 6');
INSERT INTO naucna_c.user (id, city, country, email, first_name, is_enabled, is_verified, last_name, last_password_reset_date, password, title, username) VALUES (1, 'Novi Sad', 'Serbia', 'vmosorinski@gmail.com', 'Veljko', true, true, 'Mosorinski', null, '$2a$10$sdS4tyjj41yuxYrSwQUYIeT1dOlvcBxWA8COUEYzDM18bs6.kj5Xe', 'Dipl. ing', 'veljko');
INSERT INTO naucna_c.user (id, city, country, email, first_name, is_enabled, is_verified, last_name, last_password_reset_date, password, title, username) VALUES (2, 'Novi Sad', 'Serbia', 'mihajlol@gmail.com', 'Mihajlo', true, true, 'Levarski', null, '$2a$10$zUOD59wuEsBFSBzRLVr.eO3XNGhcz9.EeIm24WddRAxE6eIjueESS', 'Dipl. ing', 'mihajlo');
INSERT INTO naucna_c.user (id, city, country, email, first_name, is_enabled, is_verified, last_name, last_password_reset_date, password, title, username) VALUES (3, 'Novi Sad', 'Serbia', 'milicamat@gmail.com', 'Milica', true, true, 'Matijevic', null, '$2a$10$wn2wzdZS2Ffrcx75OTRnye/j3VebFZomzxBJisL/0w3rdPJtYVih2', 'Dipl. ing', 'milica');
INSERT INTO naucna_c.user (id, city, country, email, first_name, is_enabled, is_verified, last_name, last_password_reset_date, password, title, username) VALUES (4, 'Belgrade', 'Serbia', 'djordjej@gmail.com', 'Djordje', true, true, 'Jovanovic', null, '$2a$10$hveZzwUYFsUwjnM/Ske/VeWEOkY0k/jwrw/DDRdnaOBDRIvztNjmm', 'Dipl. ing', 'djordje');
INSERT INTO naucna_c.user (id, city, country, email, first_name, is_enabled, is_verified, last_name, last_password_reset_date, password, title, username) VALUES (5, 'Nis', 'Serbia', 'peraperic@gmail.com', 'Petar', true, true, 'Peric', null, '$2a$10$9E7q3MXImIxCwFJj8dlkuOlEZDEHp2OovmJfolHeiot/VGD1MyzpG', 'Dipl. ing', 'petar');
INSERT INTO naucna_c.user (id, city, country, email, first_name, is_enabled, is_verified, last_name, last_password_reset_date, password, title, username) VALUES (6, 'Kragujevac', 'Serbia', 'jmarkovic@gmail.com', 'Jovan', true, true, 'Markovic', null, '$2a$10$gN0RvhS0HOqPXuuWWCDkWexm1gWxxGsjcQT.zVrhVIuw3LREfWVdi', 'Srednjoskolac', 'jovan');
INSERT INTO naucna_c.user (id, city, country, email, first_name, is_enabled, is_verified, last_name, last_password_reset_date, password, title, username) VALUES (7, 'Jagodina', 'Serbia', 'lmartinovic@gmail.com', 'Lea', true, true, 'Martinovic', null, '$2a$10$uabDAg80c3Jd6uFAoTMfR.LzOrih5DXy3X.s4tTEwjhqozh/QiiKq', 'Hemicar', 'lea');
INSERT INTO naucna_c.user (id, city, country, email, first_name, is_enabled, is_verified, last_name, last_password_reset_date, password, title, username) VALUES (8, 'Novi Sad', 'Serbia', 'd1547450@urhen.com', 'Nikola', true, true, 'Nikolic', null, '$2a$10$Aa/rpEZEyIgIByoeNxxZOOF.GyC0MYTHrXOOTMaVMppVOKX33VQ0i', null, 'nikola');
INSERT INTO naucna_c.user_magazine_redactor (redactors_id, magazine_redactor_id) VALUES (1, 1);
INSERT INTO naucna_c.user_magazine_redactor (redactors_id, magazine_redactor_id) VALUES (2, 1);
INSERT INTO naucna_c.user_magazine_redactor (redactors_id, magazine_redactor_id) VALUES (3, 2);
INSERT INTO naucna_c.user_magazine_redactor (redactors_id, magazine_redactor_id) VALUES (5, 2);
INSERT INTO naucna_c.user_magazine_reviewer (reviewer_id, magazine_reviewer_id) VALUES (3, 1);
INSERT INTO naucna_c.user_magazine_reviewer (reviewer_id, magazine_reviewer_id) VALUES (4, 1);
INSERT INTO naucna_c.user_magazine_reviewer (reviewer_id, magazine_reviewer_id) VALUES (1, 2);
INSERT INTO naucna_c.user_magazine_reviewer (reviewer_id, magazine_reviewer_id) VALUES (2, 2);
INSERT INTO naucna_c.user_roles (user_id, role_id) VALUES (1, 1);
INSERT INTO naucna_c.user_roles (user_id, role_id) VALUES (2, 1);
INSERT INTO naucna_c.user_roles (user_id, role_id) VALUES (3, 1);
INSERT INTO naucna_c.user_roles (user_id, role_id) VALUES (4, 1);
INSERT INTO naucna_c.user_roles (user_id, role_id) VALUES (5, 1);
INSERT INTO naucna_c.user_roles (user_id, role_id) VALUES (6, 1);
INSERT INTO naucna_c.user_roles (user_id, role_id) VALUES (7, 1);
INSERT INTO naucna_c.user_roles (user_id, role_id) VALUES (8, 1);
INSERT INTO paypal.client (id, client_id, paypal_client_id, paypal_secret) VALUES (2, '_CsfltCDjn-RPgxf6hHEjetUIYQDaMa8gM5hpqE-j2A', 'AQ-JUhmxs9ZQU619meknUmn6hbJoafvclUDuzcgK51w3js8VHvFK_eQOWs_i-YiBxz_nwbztqj6w_sfX', 'EKa_NIeCT-zhIbw_ZgQm8z-zEoQJUzPGD8AncNR1wuo9jzNKrt5sQBD58YglYNalV7cJKo3vCaCLoKEd');
INSERT INTO paypal.user (id, paypal_user_email, user_email) VALUES (1, 'sb-2xr2o796753@personal.example.com', 'milicamat@gmail.com');
INSERT INTO pcc.bank (id, api, name, pan, code) VALUES (1, 'https://localhost:8768/request/pay_from_pcc', 'MAIN', 'ALWPG5809L', '438163');
INSERT INTO pcc.bank (id, api, name, pan, code) VALUES (2, 'https://localhost:8766/request/pay_from_pcc', 'SECOND', 'ALWPG5701L', '406221');
INSERT INTO sellersdb.client (id, client_id, client_name, error_url, failed_url, registration_date, success_url, username) VALUES (1, 'aXx2CcgHxZP_30XSS48XxbgV_m1nbS2o_ZcUCmhx__4', 'center', 'https://localhost:8080/center/pay/error', 'https://localhost:8080/center/pay/fail', null, 'https://localhost:8080/center/pay/success', null);
INSERT INTO sellersdb.client (id, client_id, client_name, error_url, failed_url, registration_date, success_url, username) VALUES (3, '_CsfltCDjn-RPgxf6hHEjetUIYQDaMa8gM5hpqE-j2A', 'science-center', 'https://localhost:8080/center/pay/error', 'https://localhost:8080/center/pay/fail', '2020-01-29 19:15:31', 'https://localhost:8080/center/pay/success', 'marko');
INSERT INTO sellersdb.client_payment_types (client_id, payment_type_id) VALUES (1, 1);
INSERT INTO sellersdb.client_payment_types (client_id, payment_type_id) VALUES (1, 2);
INSERT INTO sellersdb.client_payment_types (client_id, payment_type_id) VALUES (1, 3);
INSERT INTO sellersdb.client_payment_types (client_id, payment_type_id) VALUES (3, 1);
INSERT INTO sellersdb.client_payment_types (client_id, payment_type_id) VALUES (3, 2);
INSERT INTO sellersdb.payment_type (id, name, service_name) VALUES (1, 'Bank', 'bank-service');
INSERT INTO sellersdb.payment_type (id, name, service_name) VALUES (2, 'PayPal', 'paypal-service');
INSERT INTO sellersdb.payment_type (id, name, service_name) VALUES (3, 'BitCoin', 'bitcoin-service');
