INSERT INTO naucna_c_second_second.magazine (id, issn, name, price, reader_pays) VALUES (1, 'issn9', 'Casopis 9', 21, true);
INSERT INTO naucna_c_second_second.magazine (id, issn, name, price, reader_pays) VALUES (2, 'issn10', 'Casopis 10', 20, false);
INSERT INTO naucna_c_second_second.magazine (id, issn, name, price, reader_pays) VALUES (3, 'issn11', 'Casopis 11', 37, true);
INSERT INTO naucna_c_second_second.magazine (id, issn, name, price, reader_pays) VALUES (4, 'issn12', 'Casopis 12', 50, false);
INSERT INTO naucna_c_second_second.magazine (id, issn, name, price, reader_pays) VALUES (5, 'issn13', 'Casopis 13', 10, true);
INSERT INTO naucna_c_second_second.magazine (id, issn, name, price, reader_pays) VALUES (6, 'issn14', 'Casopis 14', 11, false);
INSERT INTO naucna_c_second_second.magazine (id, issn, name, price, reader_pays) VALUES (7, 'issn15', 'Casopis 15', 10.5, true);
INSERT INTO naucna_c_second_second.magazine (id, issn, name, price, reader_pays) VALUES (8, 'issn16', 'Casopis 16', 12, false);
INSERT INTO naucna_c_second_second.magazine_scientific_area (magazine_list_id, scientific_area_id) VALUES (1, 1);
INSERT INTO naucna_c_second_second.magazine_scientific_area (magazine_list_id, scientific_area_id) VALUES (1, 5);
INSERT INTO naucna_c_second_second.magazine_scientific_area (magazine_list_id, scientific_area_id) VALUES (2, 2);
INSERT INTO naucna_c_second_second.magazine_scientific_area (magazine_list_id, scientific_area_id) VALUES (3, 1);
INSERT INTO naucna_c_second.magazine_scientific_area (magazine_list_id, scientific_area_id) VALUES (3, 4);
INSERT INTO naucna_c_second.magazine_scientific_area (magazine_list_id, scientific_area_id) VALUES (4, 2);
INSERT INTO naucna_c_second.magazine_scientific_area (magazine_list_id, scientific_area_id) VALUES (4, 5);
INSERT INTO naucna_c_second.magazine_scientific_area (magazine_list_id, scientific_area_id) VALUES (5, 5);
INSERT INTO naucna_c_second.magazine_scientific_area (magazine_list_id, scientific_area_id) VALUES (6, 3);
INSERT INTO naucna_c_second.magazine_scientific_area (magazine_list_id, scientific_area_id) VALUES (6, 1);
INSERT INTO naucna_c_second.magazine_scientific_area (magazine_list_id, scientific_area_id) VALUES (7, 1);
INSERT INTO naucna_c_second.magazine_scientific_area (magazine_list_id, scientific_area_id) VALUES (8, 4);
INSERT INTO naucna_c_second.publication (id, description, no, price, title, magazine_id) VALUES (1, 'Ovo je description od izdanja 1', 1, 5, 'Necete verovati sta se desilo!', 1);
INSERT INTO naucna_c_second.publication (id, description, no, price, title, magazine_id) VALUES (2, 'Ovo je description od izdanja 2', 2, 6, 'Necete verovati sta se opet desilo!', 1);
INSERT INTO naucna_c_second.role (id, name) VALUES (1, 'ROLE_USER');
INSERT INTO naucna_c_second.scentific_area (id, name) VALUES (1, 'Area 1');
INSERT INTO naucna_c_second.scentific_area (id, name) VALUES (2, 'Area 2');
INSERT INTO naucna_c_second.scentific_area (id, name) VALUES (3, 'Area 3');
INSERT INTO naucna_c_second.scentific_area (id, name) VALUES (4, 'Area 4');
INSERT INTO naucna_c_second.scentific_area (id, name) VALUES (5, 'Area 5');
INSERT INTO naucna_c_second.scentific_area (id, name) VALUES (6, 'Area 6');
INSERT INTO naucna_c_second.user (id, city, country, email, first_name, is_enabled, is_verified, last_name, last_password_reset_date, password, title, username) VALUES (1, 'Novi Sad', 'Serbia', 'vmosorinski@gmail.com', 'Veljko', true, true, 'Mosorinski', null, '$2a$10$sdS4tyjj41yuxYrSwQUYIeT1dOlvcBxWA8COUEYzDM18bs6.kj5Xe', 'Dipl. ing', 'veljko');
INSERT INTO naucna_c_second.user (id, city, country, email, first_name, is_enabled, is_verified, last_name, last_password_reset_date, password, title, username) VALUES (2, 'Novi Sad', 'Serbia', 'mihajlol@gmail.com', 'Mihajlo', true, true, 'Levarski', null, '$2a$10$zUOD59wuEsBFSBzRLVr.eO3XNGhcz9.EeIm24WddRAxE6eIjueESS', 'Dipl. ing', 'mihajlo');
INSERT INTO naucna_c_second.user (id, city, country, email, first_name, is_enabled, is_verified, last_name, last_password_reset_date, password, title, username) VALUES (3, 'Novi Sad', 'Serbia', 'milicamat@gmail.com', 'Milica', true, true, 'Matijevic', null, '$2a$10$wn2wzdZS2Ffrcx75OTRnye/j3VebFZomzxBJisL/0w3rdPJtYVih2', 'Dipl. ing', 'milica');
INSERT INTO naucna_c_second.user (id, city, country, email, first_name, is_enabled, is_verified, last_name, last_password_reset_date, password, title, username) VALUES (4, 'Belgrade', 'Serbia', 'djordjej@gmail.com', 'Djordje', true, true, 'Jovanovic', null, '$2a$10$hveZzwUYFsUwjnM/Ske/VeWEOkY0k/jwrw/DDRdnaOBDRIvztNjmm', 'Dipl. ing', 'djordje');
INSERT INTO naucna_c_second.user (id, city, country, email, first_name, is_enabled, is_verified, last_name, last_password_reset_date, password, title, username) VALUES (5, 'Nis', 'Serbia', 'peraperic@gmail.com', 'Petar', true, true, 'Peric', null, '$2a$10$9E7q3MXImIxCwFJj8dlkuOlEZDEHp2OovmJfolHeiot/VGD1MyzpG', 'Dipl. ing', 'petar');
INSERT INTO naucna_c_second.user (id, city, country, email, first_name, is_enabled, is_verified, last_name, last_password_reset_date, password, title, username) VALUES (6, 'Kragujevac', 'Serbia', 'jmarkovic@gmail.com', 'Jovan', true, true, 'Markovic', null, '$2a$10$gN0RvhS0HOqPXuuWWCDkWexm1gWxxGsjcQT.zVrhVIuw3LREfWVdi', 'Srednjoskolac', 'jovan');
INSERT INTO naucna_c_second.user (id, city, country, email, first_name, is_enabled, is_verified, last_name, last_password_reset_date, password, title, username) VALUES (7, 'Jagodina', 'Serbia', 'lmartinovic@gmail.com', 'Lea', true, true, 'Martinovic', null, '$2a$10$uabDAg80c3Jd6uFAoTMfR.LzOrih5DXy3X.s4tTEwjhqozh/QiiKq', 'Hemicar', 'lea');
INSERT INTO naucna_c_second.user (id, city, country, email, first_name, is_enabled, is_verified, last_name, last_password_reset_date, password, title, username) VALUES (8, 'Novi Sad', 'Serbia', 'd1547450@urhen.com', 'Nikola', true, true, 'Nikolic', null, '$2a$10$Aa/rpEZEyIgIByoeNxxZOOF.GyC0MYTHrXOOTMaVMppVOKX33VQ0i', null, 'nikola');
INSERT INTO naucna_c_second.user_magazine_redactor (redactors_id, magazine_redactor_id) VALUES (1, 1);
INSERT INTO naucna_c_second.user_magazine_redactor (redactors_id, magazine_redactor_id) VALUES (2, 1);
INSERT INTO naucna_c_second.user_magazine_redactor (redactors_id, magazine_redactor_id) VALUES (3, 2);
INSERT INTO naucna_c_second.user_magazine_redactor (redactors_id, magazine_redactor_id) VALUES (5, 2);
INSERT INTO naucna_c_second.user_magazine_reviewer (reviewer_id, magazine_reviewer_id) VALUES (3, 1);
INSERT INTO naucna_c_second.user_magazine_reviewer (reviewer_id, magazine_reviewer_id) VALUES (4, 1);
INSERT INTO naucna_c_second.user_magazine_reviewer (reviewer_id, magazine_reviewer_id) VALUES (1, 2);
INSERT INTO naucna_c_second.user_magazine_reviewer (reviewer_id, magazine_reviewer_id) VALUES (2, 2);
INSERT INTO naucna_c_second.user_roles (user_id, role_id) VALUES (1, 1);
INSERT INTO naucna_c_second.user_roles (user_id, role_id) VALUES (2, 1);
INSERT INTO naucna_c_second.user_roles (user_id, role_id) VALUES (3, 1);
INSERT INTO naucna_c_second.user_roles (user_id, role_id) VALUES (4, 1);
INSERT INTO naucna_c_second.user_roles (user_id, role_id) VALUES (5, 1);
INSERT INTO naucna_c_second.user_roles (user_id, role_id) VALUES (6, 1);
INSERT INTO naucna_c_second.user_roles (user_id, role_id) VALUES (7, 1);
INSERT INTO naucna_c_second.user_roles (user_id, role_id) VALUES (8, 1);
