spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bankservice?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: admin
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8765
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:bank.p12
    key-store-password: password
    client-auth: need
    trust-store: classpath:eurekaTrust.jks
    trust-store-password: password


eureka:
  client:
    serviceUrl:
      defaultZone: https://localhost:8767/eureka/
  instance:
    hostname: localhost
    preferIpAddress: false
    securePortEnabled: true
    statusPageUrl: https://${eureka.instance.hostname}:${server.port}/info
    healthCheckUrl: https://${eureka.instance.hostname}:${server.port}/health
    homePageUrl: https://localhost:${server.port}


security:
  oauth2:
    client:
      clientId: oauthorize
      clientSecret: password
      accessTokenUri: https://localhost:8081/uaa/oauth/token
      grantType: client_credentials
      scope: read write
    resource:
      userInfoUri: https://localhost:8081/uaa/user/current
      tokenInfoUri: https://localhost:8081/uaa/oauth/check_token
