spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bankservice?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: admin
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8765
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:bank.p12
    key-store-password: password
<<<<<<< HEAD
    #client-auth: need
    #trust-store: classpath:eurekaTrust.jks
    #trust-store-password: password
=======

    trust-store: classpath:eurekaTrust.jks
    trust-store-password: password
>>>>>>> c05966b8498b08fd1eea735c655c498d0bff0424

eureka:
  client:
    serviceUrl:
      defaultZone: https://localhost:8767/eureka/
  instance:
    hostname: localhost
    preferIpAddress: false
    securePortEnabled: true
    statusPageUrl: https://${eureka.instance.hostname}:${server.port}/info
    healthCheckUrl: https://${eureka.instance.hostname}:${server.port}/health
    homePageUrl: https://localhost:${server.port}


