server:
  port: 8083
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:bitcoin.p12
    key-store-password: password
    #client-auth: need
    #trust-store: classpath:eurekaTrust.jks
    #trust-store-password: password
    #key-alias: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: https://localhost:8767/eureka/
  instance:
    hostname: localhost
    preferIpAddress: false
    securePort: ${server.port}
    securePortEnabled: true
    nonSecurePortEnabled: false
    statusPageUrl: https://${eureka.instance.hostname}:${server.port}/info
    healthCheckUrl: https://${eureka.instance.hostname}:${server.port}/health
    homePageUrl: https://localhost:${server.port}
