server:
  port: 8767
  ssl:
    enabled: false
    key-store-type: PKCS12
    key-store: classpath:eureka.p12
    key-store-password: password
    client-auth: need
    trust-store: classpath:eurekaTrust.jks
    trust-store-password: password
    key-alias: localhost

eureka:
  instance:
    hostname: localhost
    securePort: ${server.port}
    securePortEnabled: true
    nonSecurePortEnabled: false
    secureVirtualHostName: ${spring.application.name}
    homePageUrl: https://${eureka.instance.hostname}:${server.port}/
    statusPageUrl: https://${eureka.instance.hostname}:${server.port}/admin/info
    metadataMap:
      hostname : ${eureka.instance.hostname}
      securePort: ${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false


