spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paypal?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: admin
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8769
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:bank.p12
    key-store-password: password
    client-auth: need
    trust-store: classpath:eurekaTrust.jks
    trust-store-password: password
    #key-alias: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: https://localhost:8767/eureka/
  instance:
    hostname: localhost
    preferIpAddress: false
    securePortEnabled: true
    statusPageUrl: https://${eureka.instance.hostname}:${server.port}/info
    healthCheckUrl: https://${eureka.instance.hostname}:${server.port}/health
    homePageUrl: https://localhost:${server.port}
