server:
  port: 8088
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:gateway.p12
    key-store-password: password
    key-alias: localhost
    client-auth: need
    trust-store: classpath:eurekaTrust.jks
    trust-store-password: password

zuul:
  routes:
    payment-system:
      url: https://localhost:8765
      path: /payment/**
      service-id: payment-system
    auth-service:
      url: https://localhost:8081
      path: /uaa/** #path that will be intercepted
      serviceId: auth-service
      stripPrefix: false #if zuul should replace the "/uaa/" segment
      sensitiveHeaders:
    registration-service:
      url: https://localhost:8082
      path: /registration/**
      serviceId: registration-service
      stripPrefix: false
      sensitiveHeaders:
    sellers-service:
      url: https://localhost:8769
      path: /sellers/**
      serviceId: sellers-service
      stripPrefix: false
      sensitiveHeaders:



eureka:
  client:
    serviceUrl:
      defaultZone: https://localhost:8767/eureka/
  instance:
    hostname: localhost
    preferIpAddress: false
    securePortEnabled: true
    statusPageUrl: https://${eureka.instance.hostname}:${server.port}/info
    healthCheckUrl: https://${eureka.instance.hostname}:${server.port}/health
    homePageUrl: https://localhost:${server.port}

