server:
  port: 8088
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:gateway.p12
    key-store-password: password
    key-alias: localhost
    client-auth: need
    trust-store: classpath:eurekaTrust.jks
    trust-store-password: password

zuul:
  routes:
    payment-system:
      url: https://localhost:8765
      path: /payment/**
      service-id: payment-system


eureka:
  client:
    serviceUrl:
      defaultZone: https://localhost:8767/eureka/
  instance:
    hostname: localhost
    preferIpAddress: false
    securePortEnabled: true
    statusPageUrl: https://${eureka.instance.hostname}:${server.port}/info
    healthCheckUrl: https://${eureka.instance.hostname}:${server.port}/health
    homePageUrl: https://localhost:${server.port}

